---
name: release

on:
  workflow_dispatch:
  release:
    types: [created]
  workflow_call:

permissions:
  contents: write
  packages: write

jobs:
  release-matrix:
    name: Release go binary

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Set PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Go Releaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ secrets.CONTAIN_BOT_PAT }}
